channels:
  - pytorch3d
  - bottler
  - pytorch
  - plotly
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - aiohttp=3.8.3
  - aiosignal=1.2.0
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - async-lru=2.0.4
  - async-timeout=4.0.2
  - attrs=23.1.0
  - babel=2.11.0
  - backcall=0.2.0
  - beautifulsoup4=4.12.2
  - blas=1.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2023.08.22
  - certifi=2023.7.22
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - colorama=0.4.6
  - cryptography=39.0.1
  - cuda=11.6.1
  - cuda-cccl=11.6.55
  - cuda-command-line-tools=11.6.2
  - cuda-compiler=11.6.2
  - cuda-cudart=11.6.55
  - cuda-cudart-dev=11.6.55
  - cuda-cuobjdump=11.6.124
  - cuda-cupti=11.6.124
  - cuda-cuxxfilt=11.6.124
  - cuda-driver-dev=11.6.55
  - cuda-gdb=12.1.105
  - cuda-libraries=11.6.1
  - cuda-libraries-dev=11.6.1
  - cuda-memcheck=11.8.86
  - cuda-nsight=12.1.105
  - cuda-nsight-compute=12.1.1
  - cuda-nvcc=11.6.124
  - cuda-nvdisasm=12.1.105
  - cuda-nvml-dev=11.6.55
  - cuda-nvprof=12.1.105
  - cuda-nvprune=11.6.124
  - cuda-nvrtc=11.6.124
  - cuda-nvrtc-dev=11.6.124
  - cuda-nvtx=11.6.124
  - cuda-nvvp=12.1.105
  - cuda-runtime=11.6.1
  - cuda-samples=11.6.101
  - cuda-sanitizer-api=12.1.105
  - cuda-toolkit=11.6.1
  - cuda-tools=11.6.1
  - cuda-visual-tools=11.6.1
  - cython=3.0.10
  - dash-renderer=0.20.0
  - dataclasses=0.8
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - ffmpeg=4.3
  - flask-compress=1.4.0
  - freetype=2.12.1
  - frozenlist=1.3.3
  - fvcore=0.1.5.post20221221
  - gds-tools=1.6.1.9
  - giflib=5.2.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - icu=58.2
  - idna=3.4
  - importlib-metadata=6.0.0
  - importlib_metadata=6.0.0
  - importlib_resources=5.2.0
  - intel-openmp=2023.1.0
  - ipython_genutils=0.2.0
  - jinja2=3.1.2
  - jpeg=9e
  - json5=0.9.6
  - jsonschema=4.17.3
  - jupyter-lsp=2.2.0
  - jupyter-server-proxy=1.0
  - jupyter_core=5.3.0
  - jupyter_events=0.6.3
  - jupyter_server_terminals=0.4.4
  - jupyterlab=4.0.5
  - jupyterlab-dash=0.1.0a2
  - jupyterlab_server=2.24.0
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libcublas=11.9.2.110
  - libcublas-dev=11.9.2.110
  - libcufft=10.7.1.112
  - libcufft-dev=10.7.1.112
  - libcufile=1.6.1.9
  - libcufile-dev=1.6.1.9
  - libcurand=10.3.2.106
  - libcurand-dev=10.3.2.106
  - libcusolver=11.3.4.124
  - libcusparse=11.7.2.124
  - libcusparse-dev=11.7.2.124
  - libdeflate=1.17
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libnpp=11.6.3.124
  - libnpp-dev=11.6.3.124
  - libnvjpeg=11.6.2.124
  - libnvjpeg-dev=11.6.2.124
  - libpng=1.6.39
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.0
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxml2=2.10.3
  - libxslt=1.1.37
  - lxml=4.9.2
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - matplotlib-inline=0.1.6
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.6
  - mkl_random=1.2.2
  - multidict=6.0.2
  - nbclient=0.8.0
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - nettle=3.7.3
  - notebook=7.0.3
  - notebook-shim=0.2.3
  - nsight-compute=2023.1.1.4
  - nvidiacub=1.10.0
  - openh264=2.1.1
  - openssl=1.1.1v
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=23.0.1
  - plotly=5.16.1
  - plotly-orca=1.3.1
  - portalocker=2.7.0
  - prompt_toolkit=3.0.43
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.15.1
  - pyopenssl=23.0.0
  - pysocks=1.7.1
  - python=3.10.11
  - python-dateutil=2.8.2
  - python-json-logger=2.0.7
  - python_abi=3.10
  - pytorch=1.13.1
  - pytorch-cuda=11.6
  - pytorch-mutex=1.0
  - pytorch3d=0.7.3
  - pyyaml=6.0
  - pyzmq=25.1.0
  - readline=8.2
  - requests=2.29.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - send2trash=1.8.2
  - setuptools=67.8.0
  - simpervisor=0.3
  - six=1.16.0
  - sniffio=1.3.0
  - sqlite=3.41.2
  - tabulate=0.9.0
  - tbb=2021.8.0
  - tenacity=8.2.2
  - termcolor=2.3.0
  - terminado=0.17.1
  - tinycss2=1.2.1
  - tk=8.6.12
  - tomli=2.0.1
  - torchaudio=0.13.1
  - torchvision=0.14.1
  - tqdm=4.65.0
  - typing-extensions=4.5.0
  - typing_extensions=4.5.0
  - urllib3=1.26.15
  - webencodings=0.5.1
  - werkzeug=2.2.3
  - wheel=0.38.4
  - xz=5.4.2
  - yacs=0.1.8
  - yaml=0.2.5
  - yarl=1.8.1
  - zeromq=4.3.4
  - zipp=3.11.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - aiofiles==0.6.0
      - ansi2html==1.8.0
      - antlr4-python3-runtime==4.9.3
      - anyio==3.7.0
      - appdirs==1.4.4
      - arrow==1.2.3
      - asttokens==2.2.1
      - bleach==6.0.0
      - click==7.1.2
      - git+https://github.com/openai/CLIP.git
      - colordict==1.2.6
      - colourmap==1.1.14
      - comm==0.1.3
      - contourpy==1.0.7
      - cycler==0.11.0
      - cython-bbox==0.1.5
      - dash==2.6.2
      - dash-core-components==2.0.0
      - dash-html-components==2.0.0
      - dash-table==5.0.0
      - distfit==1.6.10
      - docker-pycreds==0.4.0
      - git+https://github.com/epic-kitchens/epic-hand-object-detections.git
      - exceptiongroup==1.1.1
      - executing==1.2.0
      - fastjsonschema==2.17.1
      - filelock==3.12.2
      - flask==2.0.3
      - fonttools==4.39.4
      - fqdn==1.5.1
      - freetype-py==2.4.0
      - fsspec==2023.6.0
      - ftfy==6.1.1
      - gdown==5.2.0
      - gitdb==4.0.10
      - gitpython==3.1.32
      - h11==0.14.0
      - hota==0.1.0
      - httptools==0.1.2
      - huggingface-hub==0.16.2
      - imageio==2.31.0
      - iopath==0.1.10
      - ipykernel==6.23.1
      - ipython==8.14.0
      - ipywidgets==8.0.7
      - isoduration==20.11.0
      - itsdangerous==2.1.2
      - jedi==0.18.2
      - joblib==1.2.0
      - jsonpointer==2.3
      - jupyter-client==8.2.0
      - jupyter-dash==0.4.2
      - jupyter-server==2.6.0
      - jupyterlab-pygments==0.2.2
      - jupyterlab-widgets==3.0.8
      - kaleido==0.2.1
      - kiwisolver==1.4.4
      - lap==0.4.0
      - llvmlite==0.40.1
      - loguru==0.7.2
      - matplotlib==3.7.1
      - mistune==2.0.5
      - motmetrics==1.4.0
      - nbclassic==1.0.0
      - nbconvert==7.6.0
      - nbformat==5.9.0
      - networkx==3.1
      - numba==0.57.1
      - numpy==1.23.0
      - omegaconf==2.3.0
      - opencv-python==4.7.0.72
      - overrides==7.3.1
      - packaging==23.1
      - pandas==2.0.3
      - pathtools==0.1.2
      - patsy==0.5.4
      - platformdirs==3.5.1
      - prometheus-client==0.17.0
      - prompt-toolkit==3.0.38
      - protobuf==3.20.0
      - psutil==5.9.5
      - pycocotools==2.0
      - pyglet==2.0.7
      - pynndescent==0.5.10
      - pyopengl==3.1.0
      - pyparsing==3.0.9
      - pypickle==1.1.0
      - pyrender==0.1.45
      - pyrsistent==0.19.3
      - python-dotenv==1.0.0
      - pytz==2023.3
      - regex==2023.6.3
      - retrying==1.3.4
      - rtree==1.0.1
      - safetensors==0.3.1
      - scikit-learn==1.4.1.post1
      - scipy==1.10.1
      - seaborn==0.12.2
      - sentry-sdk==1.29.2
      - setproctitle==1.3.2
      - shapely==2.0.2
      - smmap==5.0.0
      - soupsieve==2.4.1
      - stack-data==0.6.2
      - starlette==0.14.2
      - statsmodels==0.14.0
      - thop==0.1.1-2209072238
      - threadpoolctl==3.1.0
      - tokenizers==0.13.3
      - tornado==6.3.2
      - traitlets==5.9.0
      - transformers==4.30.2
      - trimesh==3.22.0
      - tzdata==2023.3
      - umap-learn==0.5.3
      - uri-template==1.2.0
      - uvicorn==0.13.4
      - uvloop==0.17.0
      - wandb==0.15.8
      - watchgod==0.8.2
      - wcwidth==0.2.6
      - webcolors==1.13
      - websocket-client==1.5.2
      - websockets==8.1
      - widgetsnbextension==4.0.8
      - xmltodict==0.13.0
